# Generated by Django 5.1.3 on 2024-11-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Editor', 'Editor'), ('Viewer', 'Viewer')], default='Viewer', max_length=50, unique=True),
        ),
    ]
